### ISSUE TITLE
noSourceMap option cannot be set -- no error message

### ISSUE THREAD

**Issue by fono** [cleydyr/dart-sass-maven-plugin#1]
When setting `noSourceMap` option, the build fails because `AbstractSassCommand` also passes `--source-map-urls` option to the executable. It returns with exit code 64 with no other error message in the log.

To get to what its problem was I had to debug the plugin to get the executed command, and call it from command line to see the actual error message returned by the executable. It seems that the error message is printed on the standard out (along with the usage instructions).

Please note I'm on Apple Silicon. Maybe Windows handles the process outputs differently.

**Comment by cleydyr** [comment]
Hey, @fono . Thanks for reporting this issue. I can confirm that the behavior is reproducible given the description you gave.

**Comment by cleydyr** [comment]
Should be fixed in version 0.1.0. I'm closing this issue now. Thank you!
