### ISSUE TITLE
Watch goal

### ISSUE THREAD

**Issue by NicolaIsotta** [cleydyr/dart-sass-maven-plugin#11]
A "watch" goal would be a useful addition.
Example from a Ruby Sass plugin: https://geodienstencentrum.github.io/sass-maven-plugin/watch-mojo.html

**Comment by melloware** [comment]
+1 on this a Watch goal would be awesome so I can replace the same plugin reference above

**Comment by melloware** [comment]
I am also wondering if the Maven goals should be similar to the other plugin...

`mvn sass:compile`
`mvn sass:watch`

**Comment by cleydyr** [comment]
Should is too strong a word. :D The documentation is clear about the goals' names, so I'll stick to it for now.

**Comment by cleydyr** [comment]
By the way, the watch goal functionality has been pushed to master. It will be included in the next release.

**Comment by melloware** [comment]
HA yes should is a strong word :)  Nice work on the watch!
