### ISSUE TITLE
Watch: Not watching correct directory

### ISSUE THREAD

**Issue by melloware** [cleydyr/dart-sass-maven-plugin#18]
Trying to run ...

```
mvn io.github.cleydyr:dart-sass-maven-plugin:0.2.0:watch-sass
```

I am getting this its looking at `src\main\sass` and its not looking at my plugin config for which directory unless I am doing something wrong.

```
[INFO] --- dart-sass-maven-plugin:0.2.0:watch-sass (default-cli) @ primefaces-showcase ---
Error reading src\main\sass: Cannot open file.

Sass is watching for changes. Press Ctrl-C to stop.
```

**Comment by cleydyr** [comment]
Hey, @melloware. Can you post the relevant configuration section of your pom.xml file so that I can check it out?

**Comment by melloware** [comment]
Sure its right here: https://github.com/primefaces/primefaces/blob/master/primefaces-showcase/pom.xml

**Comment by cleydyr** [comment]
Ok. So, I guess by invoking `mvn io.github.cleydyr:dart-sass-maven-plugin:0.2.0:watch-sass` directly maven is not supposed to get the configuration from your pom.xml. Or is it?

**Comment by melloware** [comment]
that is how `sass:watch` worked in the old plugin.  It used your pom.xml config for the watch.

**Comment by cleydyr** [comment]
I see that if you put the configuration inside a specific execution, you'll have to specify the execution id when calling the plugin. So, in your case it should be `dart-sass:watch-sass@generate-css-using-sass`. If you simply call `dart-sass:watch-sass` (or its fully qualified equivalent), then only the general plugin config will be read.

Does it make sense?

**Comment by melloware** [comment]
Yep that works.  Can you update the readme I don't think others would figure that out!

**Comment by cleydyr** [comment]
Isn't it the the expected Maven behavior?

**Comment by melloware** [comment]
so i am just going on the old Ruby sass plugin where once it was configured in the pom.xml you could run `sass:watch` or `sass:compile` and both used the plugins values from the pom.xml regardless of execution cycle.  

I look at it as the plugin is configured in the pom.xml.  It has a default lifecycle but any calls to the plugin should execute based on the configuration in the pom.xml by default.  I thought that is is how most Maven plugins work?

**Comment by cleydyr** [comment]
I've checked https://maven.apache.org/pom.html and the executions example corroborates my hypothesis.

Consider this sample:

```
<plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>1.1</version>
        <executions>
          <execution>
            <id>echodir</id>
            <goals>
              <goal>run</goal>
            </goals>
            <phase>verify</phase>
            <inherited>false</inherited>
            <configuration>
              <tasks>
                <echo>Build Dir: ${project.build.directory}</echo>
              </tasks>
            </configuration>
          </execution>
        </executions>
 
      </plugin>
```
If I add it to a project's pom.xml, then execute `antrun:run` the echo task is not executed, while if I execute `antrun:run@echodir`, then the echo task is executed.

Is there something I'm missing in this case?

**Comment by melloware** [comment]
Hmmm so this was the plugin configuration we used before switching to your plugin...

```xml
         <plugin>
                <groupId>nl.geodienstencentrum.maven</groupId>
                <artifactId>sass-maven-plugin</artifactId>
                <version>3.7.2</version>
                <executions>
                    <execution>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>update-stylesheets</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sassSourceDirectory>${basedir}/src/main/webapp/resources/showcase/css</sassSourceDirectory>
                    <destination>${basedir}/src/main/webapp/resources/showcase/css</destination>
                    <sassOptions>
                        <always_update>true</always_update>
                        <sourcemap>:none</sourcemap>
                    </sassOptions>
                </configuration>
            </plugin>
```


Same as yours has an execution and goals.  However if I ran `mvn sass:watch` it watched the correct directory using the plugin's config.  

Same is if I run the `mvn war:war` plugin it uses the pom.xml even though that has an execution and goals as well.  It builds the war based on the pom.xml config.

**Comment by cleydyr** [comment]
The issue is not having an execution. The issue is having an execution X, putting the plugin configuration _inside_ that execution X and then invoking the plugin without specifying the execution X. Notice that your old plugin configuration was _outside_ the execution.

**Comment by melloware** [comment]
HA i didn't even noticed that I cut and pasted your example.  I just moved it outside of the execution and it works!

Whoops!

**Comment by melloware** [comment]
Works exactly like the old plugin now but **WAY** faster.  Thanks again for your great work.
