### ISSUE TITLE
Update executables with latest Dart Sass release

### ISSUE THREAD

**Issue by cleydyr** [cleydyr/dart-sass-maven-plugin#23]
Use https://github.com/sass/dart-sass/releases/latest.

Source https://github.com/cleydyr/dart-sass-maven-plugin/issues/21

**Comment by melloware** [comment]
Also might want to read this thread about automatically pulling and caching the DART EXE's?
https://github.com/sass/sass-site/issues/660

**Comment by cleydyr** [comment]
Hey, @melloware. Thanks for the hint. I learned about that other plugin a while ago, but I don't know if it's worth adding that functionality instead of publishing new plugin versions as needed. I'll think about it for a while, but let me know if you have a case for the addition of this functionality.

**Comment by ennerf** [comment]
> I don't know if it's worth adding that functionality instead of publishing new plugin versions as needed

The plugin is already many versions out of date, and new plugin releases are going to be spaced out even more the more stable it becomes. It's not much effort to add the extra ~50 lines of code for the on-demand download, so IMO that's absolutely worth it.

Just check how many issues in the [protoc-jar-maven-plugin](https://github.com/os72/protoc-jar-maven-plugin/issues) are related to the built-in version being outdated (e.g. all of the macOS M1 build issues). For a wrapper plugin I think it's best to keep the maintenance effort to a bare minimum, especially if the wrapped executable is released on a weekly schedule.

**Comment by cleydyr** [comment]
Hi,

I'm closing this case as it was supposed to track the update of the wrapped Dart Sass cli version, which has been done with the release of version v0.4.0. Subscribe to https://github.com/cleydyr/dart-sass-maven-plugin/issues/29 to follow the progress of the new feature.

Thanks

**Comment by cleydyr** [comment]
Released on version 1.0.0.
