### ISSUE TITLE
noSourceMap isn't working

### ISSUE THREAD

**Issue by nkavian** [cleydyr/dart-sass-maven-plugin#27]
This plugin is wonderful!

I'm using `<noSourceMap>true</noSourceMap>` but a source map is still being generated.

It's being executed through Eclipse using `org.eclipse.m2e:lifecycle-mapping` but the other settings I have are being honored.

```
                <configuration>
                    <inputFolder>${project.basedir}/src/main/resources/sass/</inputFolder>
                    <noSourceMap>true</noSourceMap>
                    <outputFolder>${project.basedir}/src/main/resources/static/css/</outputFolder>
                    <style>EXPANDED</style>
                    <update>true</update>
                </configuration>
```

**Comment by nkavian** [comment]
Closing. Actual all of a sudden I can't reproduce it. Rebuilding a few times and the map isn't being generated any more.

**Comment by cleydyr** [comment]
Thank you for your feedback, @nkavian. I really appreciate it. I'm glad that what initially appeared to be a bug vanished, and now you can continue your development work. Please don't hesitate to let me know if you face any issues in the future.
