### ISSUE TITLE
[enhancement] support maven proxy settings

### ISSUE THREAD

**Issue by gbrinkmann** [cleydyr/dart-sass-maven-plugin#30]
It looks like the plugin is not using maven proxy settings when trying to download sass from Github.
We added explicit proxy settings to a Bamboo maven task, now sass is cached.

Best regards and thanks for this plugin.

**Comment by cleydyr** [comment]
Hey, @gbrinkmann . Thanks for opening this issue. On version 1.0.0 the plugin doesn't accept proxy settings. I'll release this enhancement in the next release of the plugin. Unfortunately, for now, we won't be able to reuse the Maven settings as I couldn't figure out how to get the proxy configuration object from inside my plugin.

**Comment by gbrinkmann** [comment]
Hi @cleydyr , would maybe https://github.com/ScrapCodes/effective-pom-plugin/blob/master/src/main/java/org/apache/spark/EffectivePomMojo.java be helpful with this?
[edit] sorry, looks like settings are not available here

**Comment by cleydyr** [comment]
Hey, @gbrinkmann . I think auto-wiring a [MavenSettingsBuilder](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/settings/MavenSettingsBuilder.java) (which probably will be [DefaultMavenSettingsBuilder.java](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/settings/DefaultMavenSettingsBuilder.java)) and getting a Settings instance from it will do the trick to find the proxy settings.

**Comment by gbrinkmann** [comment]
Hi @cleydyr , good luck, should be possible in a plugin (there's also a mvn help:effective-settings which includes proxy settings)

**Comment by cleydyr** [comment]
It's out on version 1.1.0. Closing this.

**Comment by gbrinkmann** [comment]
Hello @cleydyr and thank you, my successful testing steps are

- npm uninstall -g sass
- removed C:\Users\...\AppData\Local\dart-sass-maven-plugin
- corrected our proxy host name in my mvn settings.xml
- use plugin version 1.1.0
- mvn clean install
- worked like a charm
