### ISSUE TITLE
Permission Denied when executing

### ISSUE THREAD

**Issue by arnis87** [cleydyr/dart-sass-maven-plugin#32]
We have issue that when running the plugin on our build server it no longer works due to following error:
`Caused by: java.io.IOException: Cannot run program "/tmp/dart-sass-maven-plugin/linux/x64/1.69.3/sass": error=13, Permission denied`

Currently running on version `1.1.0` but this worked in `0.3.0` - have not tried verisons in between.

Is this something that can be fixed in the plugin or is it configuration issue?

**Comment by melloware** [comment]
Can you try 1.2.0 which is the latest?

**Comment by arnis87** [comment]
Same with 1.2.0

**Comment by melloware** [comment]
OK thanks for checking.

**Comment by cleydyr** [comment]
Hey, @arnis87. Thanks for reporting this. Thank you @melloware as well for suggesting the customer use the latest version of the plugin.

Can you clean the /tmp/dart-sass-maven-plugin folder and try running the build again?

**Comment by arnis87** [comment]
No probably not - unfortunaltely I do not have direct access

**Comment by cleydyr** [comment]
@arnis87, can you provide a minimal example to reproduce the behavior?

The compile and extract logic is executed in the tests (see https://github.com/cleydyr/dart-sass-maven-plugin/blob/master/src/test/java/com/github/cleydyr/dart/maven/plugin/CompileSassMojoTest.java#L36, for example). I might be missing a detail, but if it was consistently reproducible, it would emerge during our CI tests.

**Comment by arnis87** [comment]
No. It seems to be somehow related to that specific environment but I do not have access there. We do have other linux based build systems where the problem does not occur. 
Given that the error is "Permission denied" perhaps this has something to do with how `/tmp` directory is setup. Would it be an option to make the directory, where sass is downloaded to and run, a configuration option?

**Comment by cleydyr** [comment]
Unfortunately, adding that feature would cover the real problem of how that server instance is set up. It might even cover a problem with the plugin itself; we need to find out.

Please provide more details about how the server is set up, and we can try to figure out what's happening.

**Comment by melloware** [comment]
Agreed. If you don't have permissions to Java IO Temp then you have bigger issues on that server that should not be solved by the plug-in. Changing your temp dir to something your user has permission to is the right answer

**Comment by cleydyr** [comment]
I'm closing this until we have evidence that the plugin is causing the problem.
