### ISSUE TITLE
Use Release tags instead of plain tags to mark new versions

### ISSUE THREAD

**Issue by chovyy** [cleydyr/dart-sass-maven-plugin#38]
Dear @cleydyr, can you please use the Release feature of GitHub to mark new versions? That would enable users to receive notifications upon new releases:

![grafik](https://github.com/cleydyr/dart-sass-maven-plugin/assets/26480844/626a482f-dc7a-479d-a6f7-9250be2de899)

**Comment by cleydyr** [comment]
Done. Published the first GH release v1.4.0.

**Comment by chovyy** [comment]
Great. Thanks a lot! :-)
