### ISSUE TITLE
dart-sass-maven-plugin 1.77.4 is not a Win32 valid application

### ISSUE THREAD

**Issue by dani-arm** [cleydyr/dart-sass-maven-plugin#43]
Since May the 30th, 2024, when compiling with this plugin, I receive a Windows error which says:

"[temp path]...no es una aplicación win32 válida".

I have Win 64 bits, and it seems that the plug-in correctly detects it (as the temp path, where the plugin puts dart.exe, contains x64 folder) but when compiling, the error mentioned appears.

Following the code published here, I guess this plug-in uses https://github.com/sass/dart-sass/releases/download/1.77.4/dart-sass-1.77.4-windows-x64.zip resource and extracts dart.exe from that source and download it to my temporary path (mentioned above), which as I could see has been modified exactly in May the 30th 2024.

I'm stucked with it. Could anyone please help me to solve this problem? I strongly need to compile my .sass files back again.

Thanks in advance.

Dani.-
![dart-error](https://github.com/cleydyr/dart-sass-maven-plugin/assets/172282288/a316eb05-cce2-4599-bf7d-758a375298e6)

**Comment by cleydyr** [comment]
Hey, @dani-arm .

Did you try running the Dart Sass executable for Windows x64 directly without the plugin?

**Comment by dani-arm** [comment]
Yes, and same error appears... before May the 30th no error appeared and compiled it right.

**Comment by cleydyr** [comment]
If you get the same results without the plugin, we can rule out the plugin as the source of the problem. Please do the following basic troubleshooting steps:

* try compiling on another machine
* try with another Dart Sass version (use the <version> configuration as explained in [the documentation](https://github.com/cleydyr/dart-sass-maven-plugin?tab=readme-ov-file#parameter-details))
* clean your temp (`%TEMP%\dart-sass-maven-plugin`) and cache (`%LOCALAPPDATA%\dart-sass-maven-plugin\Cache`) folders

**Comment by dani-arm** [comment]
I tried dart-sass version 1.71.1 and it works again! The point is that the latest version of dart-sass (today 1.77.4) uses DART 3.4 which needs Windows 10 or higher, while I use Windows 7.

You can see more details on: https://github.com/sass/dart-sass/issues/2261#issue-2343992998

So thank you for your support! Issue solved!
