### ISSUE TITLE
dart: not found

### ISSUE THREAD

**Issue by tubbynl** [cleydyr/dart-sass-maven-plugin#44]
some if my Gitlab CI pipeline builds fail on this plugin, it seems flaky / not consistent.

error
```
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8/sass: exec: line 20: /tmp/dart-sass-maven-plugin/linux/x64/1.77.8/src/dart: not found
```

my environment
- gitlab CI
- build container maven:3.9-eclipse-temurin-21-alpine

on some projects it's ok
```
[INFO] --- dart-sass:1.3.1:compile-sass (generate-css-using-sass) @ server ---
[INFO] Auto-detected operating system: linux
[INFO] Auto-detected operating system architecture: x64
[INFO] Auto-detected latest version: 1.77.8
[INFO] Auto-detected cached files directory: /root/.dart-sass-maven-plugin
[INFO] Compiled 3 files in 55 ms
```
on some projects not
```
[INFO] --- dart-sass:1.3.1:compile-sass (generate-css-using-sass) @ server ---
[INFO] Auto-detected operating system: linux
[INFO] Auto-detected operating system architecture: x64
[INFO] Auto-detected cached files directory: /root/.dart-sass-maven-plugin
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8/sass: exec: line 20: /tmp/dart-sass-maven-plugin/linux/x64/1.77.8/src/dart: not found
```
observations
- it's consistent per project (it either works and keeps working or it doesnt), that's probably relatable to the local cache
- setting <version> in config doesnt help (tried multiple 1.77ish versions)
- switching dart-sass-maven-plugin versions doesnt help
- In the debug log it does seem to start downloading the binary (but the build logs end because of the amout of binary content in the logs)

i'm still debugging but i was wondering if there's logging (other than -X) which can be enabled?

**Comment by cleydyr** [comment]
Hey, @tubbynl. 

Is it possible to add to the pipeline an `ls -laR /tmp/dart-sass-maven-plugin/linux/x64/1.77.8` command and share the output here? I suspect the plugin is not resilient enough to detect missing files in the temporary directory.

As a workaround, you can add a step to delete the entire /tmp/dart-sass-maven-plugin in your pipeline. That won't add a significant delay to your pipeline as the plugin keeps a tarball cache in the user directory as well; the additional delay would be to extract the tarball again.

**Comment by tubbynl** [comment]
```
$ ls -laR /tmp/dart-sass-maven-plugin/linux/x64/1.77.8
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8:
total 16
drwxr-xr-x    3 root     root          4096 Sep  2 08:02 .
drwxr-xr-x    3 root     root          4096 Sep  2 08:02 ..
-r-x------    1 root     root           592 Sep  2 08:02 sass
drwxr-xr-x    2 root     root          4096 Sep  2 08:02 src
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8/src:
total 9580
drwxr-xr-x    2 root     root          4096 Sep  2 08:02 .
drwxr-xr-x    3 root     root          4096 Sep  2 08:02 ..
-r-x------    1 root     root       4805728 Sep  2 08:02 dart
-r-x------    1 root     root       4991240 Sep  2 08:02 sass.snapshot
```

**Comment by tubbynl** [comment]
tnx for your help btw :) 

```
 rm -f ~/.dart-sass-maven-plugin
rm -f /tmp/dart-sass-maven-plugin
```
rm beforehand does not seem to make a difference, ls'ing them confirms they don't exist before start of `mvn compile` 
it almost seems like a user/privilege issue but the chmod seem ok

output of `ls -laR ~/.dart-sass-maven-plugin`
```
ls -laR ~/.dart-sass-maven-plugin
/root/.dart-sass-maven-plugin:
total 12
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 .
drwx------    1 root     root          4096 Sep  2 08:13 ..
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 linux
/root/.dart-sass-maven-plugin/linux:
total 12
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 .
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 ..
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 x64
/root/.dart-sass-maven-plugin/linux/x64:
total 12
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 .
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 ..
drwxr-xr-x    2 root     root          4096 Sep  2 08:13 1.77.8
/root/.dart-sass-maven-plugin/linux/x64/1.77.8:
total 3684
drwxr-xr-x    2 root     root          4096 Sep  2 08:13 .
drwxr-xr-x    3 root     root          4096 Sep  2 08:13 ..
-rw-r--r--    1 root     root       3762080 Sep  2 08:13 release
```
for comparison i also ran the ls command in a pipeline where the plugin functions correctly (plugin version and build container image are the same)
```
$ ls -laR /tmp/dart-sass-maven-plugin
/tmp/dart-sass-maven-plugin:
total 16
drwxr-xr-x 3 root root 4096 Sep  2 08:35 .
drwxrwxrwt 1 root root 4096 Sep  2 08:35 ..
drwxr-xr-x 3 root root 4096 Sep  2 08:35 linux
/tmp/dart-sass-maven-plugin/linux:
total 12
drwxr-xr-x 3 root root 4096 Sep  2 08:35 .
drwxr-xr-x 3 root root 4096 Sep  2 08:35 ..
drwxr-xr-x 3 root root 4096 Sep  2 08:35 x64
/tmp/dart-sass-maven-plugin/linux/x64:
total 12
drwxr-xr-x 3 root root 4096 Sep  2 08:35 .
drwxr-xr-x 3 root root 4096 Sep  2 08:35 ..
drwxr-xr-x 3 root root 4096 Sep  2 08:35 1.77.8
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8:
total 16
drwxr-xr-x 3 root root 4096 Sep  2 08:35 .
drwxr-xr-x 3 root root 4096 Sep  2 08:35 ..
-r-x------ 1 root root  592 Sep  2 08:35 sass
drwxr-xr-x 2 root root 4096 Sep  2 08:35 src
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8/src:
total 9580
drwxr-xr-x 2 root root    4096 Sep  2 08:35 .
drwxr-xr-x 3 root root    4096 Sep  2 08:35 ..
-r-x------ 1 root root 4805728 Sep  2 08:35 dart
-r-x------ 1 root root 4991240 Sep  2 08:35 sass.snapshot
```

**Comment by tubbynl** [comment]
interesting; if i switch build image from `maven:3.9-eclipse-temurin-21-alpine` to `maven:3.9-eclipse-temurin-21` it seems to be working, so i'm guessing the os-detection on the `maven:3.9-eclipse-temurin-21-alpine` is the direction to look for; what binary should it download for alpine?

```
[INFO] --- dart-sass:1.3.1:compile-sass (generate-css-using-sass) @ server ---
[INFO] Auto-detected operating system: linux
[INFO] Auto-detected operating system architecture: x64
[INFO] Auto-detected cached files directory: /root/.dart-sass-maven-plugin
[INFO] Compiled 1 files in 23 ms
```

```
$ ls -laR /tmp/dart-sass-maven-plugin
/tmp/dart-sass-maven-plugin:
total 16
drwxr-xr-x 3 root root 4096 Sep  2 09:08 .
drwxrwxrwt 1 root root 4096 Sep  2 09:08 ..
drwxr-xr-x 3 root root 4096 Sep  2 09:08 linux
/tmp/dart-sass-maven-plugin/linux:
total 12
drwxr-xr-x 3 root root 4096 Sep  2 09:08 .
drwxr-xr-x 3 root root 4096 Sep  2 09:08 ..
drwxr-xr-x 3 root root 4096 Sep  2 09:08 x64
/tmp/dart-sass-maven-plugin/linux/x64:
total 12
drwxr-xr-x 3 root root 4096 Sep  2 09:08 .
drwxr-xr-x 3 root root 4096 Sep  2 09:08 ..
drwxr-xr-x 3 root root 4096 Sep  2 09:08 1.77.8
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8:
total 16
drwxr-xr-x 3 root root 4096 Sep  2 09:08 .
drwxr-xr-x 3 root root 4096 Sep  2 09:08 ..
-r-x------ 1 root root  592 Sep  2 09:08 sass
drwxr-xr-x 2 root root 4096 Sep  2 09:08 src
/tmp/dart-sass-maven-plugin/linux/x64/1.77.8/src:
total 9580
drwxr-xr-x 2 root root    4096 Sep  2 09:08 .
drwxr-xr-x 3 root root    4096 Sep  2 09:08 ..
-r-x------ 1 root root 4805728 Sep  2 09:08 dart
-r-x------ 1 root root 4991240 Sep  2 09:08 sass.snapshot
```

**Comment by tubbynl** [comment]
setting `os` to `linux-musl` doesn't seem to help; i think it originates here https://github.com/sass/dart-sass-embedded/issues/106 in my case switch to `maven:3.9-eclipse-temurin-21` fixes this issue

only thing to implement here will be to improve os detection so it can fail with a message that this OS is not supported, will you accept a PR on this?

**Comment by cleydyr** [comment]
Nice catch, @tubbynl . Using the `maven:3.9-eclipse-temurin-21-alpine` and running `System.getProperty("os.name");` on `jshell` I get `"Linux"` as the return value. However, this plugin expects either `"macos"`, `"windows"`, or `"linux"` (notice the lowercase initial letter) as the return value for that method call.

I'm unsure if returning "Linux" is expected of JDK implementations or if I should change the plugin code to make the comparison case-insensitive to accommodate that exception.

**Comment by cleydyr** [comment]
Scratch that. 🤦 

[Actually](https://github.com/cleydyr/dart-sass-maven-plugin/blob/master/src/main/java/com/github/cleydyr/dart/system/OSDetector.java#L54-L66), the plugin verifies if the `os.name` _contains_ "Mac OS" or "Windows". If not, it falls back to Linux. There may be a place where the letter case is important. I'll check that out.

**Comment by cleydyr** [comment]
I used a test project with both both the `maven:3.9-eclipse-temurin-21-alpine` and the `maven:3.9-eclipse-temurin-21` Docker images and I could `mvn compile` them without problems. There is a Github Action that does the same and it's passing.

> setting os to linux-musl doesn't seem to help

Please share the output of running the plugin with the os configuration set.

**Comment by tubbynl** [comment]
i forked this project on gitlab for fiddling purposes and there it failed. Let me share that

**Comment by tubbynl** [comment]
ok; i forked this project on gitlab and added a ci file https://gitlab.com/tub/dart-sass-maven-plugin/-/tree/feature/example-ci-pipeline?ref_type=heads
- green: https://gitlab.com/tub/dart-sass-maven-plugin/-/jobs/7732583977
- red: https://gitlab.com/tub/dart-sass-maven-plugin/-/jobs/7732675259

**Comment by cleydyr** [comment]
Hey, @tubbynl .

Unfortunately, I can't access any of the links you posted. Please share the output of running the plugin with the os configuration set.

**Comment by tubbynl** [comment]
sorry, the gitlab repo was private; i've made it public

https://gitlab.com/tub/dart-sass-maven-plugin/-/commits/feature/example-ci-pipeline

this project on gitlab-ci running with alpine tests green if OS set to linux-musl manually (see commits for diffs, i haven't looked into your tests and how they work)

- https://gitlab.com/tub/dart-sass-maven-plugin/-/commit/1eee9f754a845a2be2d1173ad22f6f2ace77ffbc is green (running with maven:3.9-eclipse-temurin-11-alpine but and setting OS to linux-musl)
- https://gitlab.com/tub/dart-sass-maven-plugin/-/commit/0e9c306736a902ca1177e70d5f18a31042c8dfd4 is red (running with maven:3.9-eclipse-temurin-11-alpine but not setting OS to linux-musl)
- https://gitlab.com/tub/dart-sass-maven-plugin/-/commit/902b8dc79248bc4cb182a2142b87fbc5692cc3f4 is green (this project with a minimal gitlab-ci pipeline running with maven:3.9-eclipse-temurin-11)

**Comment by tubbynl** [comment]
or see #45

**Comment by cleydyr** [comment]
So, can you confirm that the problem is solved either by

1. setting the `os` plugin configuration parameter to `linux-musl` when using an alpine-derived image; or
2. not using an alpine-derived image?

**Comment by tubbynl** [comment]
yes, i can confirm both 1 and 2 at the moment

remaining feature request would be to detect the alpine derived image's and set `os` plugin configuration to `linux-musl` part of the os-detection (built in #36 ) 

but i'm guessing detecting that is hard based on  `os.name` only

correction it's harder; they seem to having something implemented in sqlite for this problem: https://github.com/xerial/sqlite-jdbc/pull/675

**Comment by tubbynl** [comment]
thank you for your time, i think the remaining changes in #45 make sense , please review :)

**Comment by cleydyr** [comment]
Thank you for going through this issue and suggesting improvements. I'll check your PR eventually.

**Comment by cleydyr** [comment]
Solved by adopting one of the alternatives [here](https://github.com/cleydyr/dart-sass-maven-plugin/issues/44#issuecomment-2342040720).
