### ISSUE TITLE
Add autodetection capability to Linux systems using musl

### ISSUE THREAD

**Issue by cleydyr** [cleydyr/dart-sass-maven-plugin#46]
As a user of Linux OSes with musl (like the ones used in Alpine Docker images, see https://github.com/cleydyr/dart-sass-maven-plugin/issues/44), I'd like the Dart Sass Maven Plugin to autodetect if the operating system uses musl.

**Comment by tubbynl** [comment]
something similar was implemented in sqlite for this problem: https://github.com/xerial/sqlite-jdbc/pull/675 , but some research is required, i would expected there's a lib for this

**Comment by cleydyr** [comment]
Hey, @tubbynl. See #47 .
