### ISSUE TITLE
Add `skip` option

### ISSUE THREAD

**Issue by chovyy** [cleydyr/dart-sass-maven-plugin#48]
Sometimes, I don't want the Dart Sass Plugin to be executed, because I just want to run `mvn test` without building any frontend stuff or I am in an environment, where I don't have access to the Dart Sass backend.

It's common, that Maven plugins have a `skip` option for such situations. It would be nice if you could introduce such an option in the Dart Sass Maven Plugin.

**Comment by melloware** [comment]
+1

**Comment by cleydyr** [comment]
Thanks for the suggestion. It's been implemented by https://github.com/cleydyr/dart-sass-maven-plugin/commit/4f93a97e4e4ecd5a916305ac65222b8391206f05.

**Comment by cleydyr** [comment]
Released with [v1.5.0](https://github.com/cleydyr/dart-sass-maven-plugin/releases/tag/v1.5.0). Closing this now.

**Comment by chovyy** [comment]
Great. Thanks a lot for the skip response! :-)
